### ISSUE TITLE
[init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [DO-SOPT-Seminar-Web-6/WatchaPedia-Server#1]
## Issue 📌
프로젝트 초기 세팅

## Todo ✔️
- [x] Issue 템플릿 추가
- [x] PR 템플릿 추가
- [x] Label 생성
- [x] Branch Rule 설정
- [x] .gitignore 설정
- [x] ERD 설계
- [x] 인프라 아키텍처 설계
- [x] 도메인 발급
- [x] SSL 인증서 발급
- [x] EC2 세팅
- [x] RDS 세팅
- [x] Nginx 세팅
- [x] CI/CD 세팅
- [x] 스프링 부트 프로젝트 업로드
- [x] 프로젝트 초기 세팅
- [x] Readme 초안 작성
